### ISSUE TITLE
how to config `log_sample.json` file?

### ISSUE THREAD

**Issue by erxiong0** [shuhao02/RouterDC#2]
I found that in the project ```bigcode-evaluation-harness```, there's no `--log_sample_path` which seems important to train router in main.py. How can I complement this function to get log_sample file?

**Comment by shuhao02** [comment]
Hi, thank you for pointing it out.

We are sorry for losing these implement details, we slightly modify the `bigcode-evaluation-harness` to log the per-sample score. 

Here is an example to log the output of **humaneval**:  
https://github.com/bigcode-project/bigcode-evaluation-harness/issues/215#issuecomment-2044445209

You can also log the output of samples in other datasets by changing the corresponding task python file.

**Comment by erxiong0** [comment]
it works, thanks!
